spring.application.name=my-portafolio-backend

# URL con el prefijo jdbc: y el puerto 5432 de PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-polished-river-aywv7mqy-pooler.c-5.us-east-2.aws.neon.tech:5432/portfolio?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_KE2VxgSckD7C

# Configuración del pool Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always